### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by einalex** [samuelyeewl/zotrm#11]
```
Traceback (most recent call last):
  File "/home/user/git/projects/Remarkable/zotrm/zotrm/zotrm.py", line 538, in <module>
    main(args.verbose, args.landscape, args.dry_run)
  File "/home/user/git/projects/Remarkable/zotrm/zotrm/zotrm.py", line 526, in main
    backsync_papers(zot, rmapi, config, verbose=verbose, dry_run=dry_run, exclude=sent_papers)
  File "/home/user/git/projects/Remarkable/zotrm/zotrm/zotrm.py", line 420, in backsync_papers
    os.remove(annotate_files[0])
NameError: name 'annotate_files' is not defined
```
needs to be 'annotated_files' with a d

**Comment by samuelyeewl** [comment]
Fixed in 07b9ddc
